---
run:
  concurrency: 6
  timeout: 5m

issues:
  exclude-rules:
    - path: fake_.*\.go
      linters:
        - gocritic
        - dupl

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - execinquery
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nakedret
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - promlinter
    - protogetter
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - testableexamples
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint

linters-settings:
  gocritic:
    enabled-checks:
      - appendCombine
      - boolExprSimplify
      - builtinShadow
      - commentFormatting
      - dupImport
      - evalOrder
      - hugeParam
      - importShadow
      - rangeValCopy
      - typeUnparen
      - unnecessaryBlock
      - weakCond

  gocyclo:
    min-complexity: 15

  staticcheck:
    checks: ["all", "-ST1000"]

  revive:
    ignore-generated-header: false
    severity: warning
    confidence: 0.8
    rules:
      - name: unreachable-code
        severity: error

  errcheck:
    check-type-assertions: true
    check-blank: true

  gofmt:
    simplify: true

  nolintlint:
    require-specific: true
    require-explanation: true
