kind: carbonaut
meta:
    name: carbonaut
spec:
    provider:
        - kind: energy-provider
          meta:
            name: scaphandre-1
            provider: scaphandre
          spec:
            endpoints:
                - http://localhost:8080/metrics
        - kind: geolocation-provider
          meta:
            name: ipapi-1
            provider: ipapi
          spec:
            ipaddresses:
                - 8.8.8.8
        - kind: emission-provider
          meta:
            name: energy-map-1
            provider: energy-map
          spec:
            geolocation:
                country: ""
                countrycode: ""
                region: DE
                regionname: ""
                city: ""
                zip: ""
                lat: 0
                lon: 0
                ip: ""
            energy:
                - amount: 2.669267e+06
                  unit: milliwatt
                  name: Host
    server:
        metricsPort: 8082
        collectorName: carbonaut
