kind: carbonaut
meta:
    name: carbonaut
    log_level: debug
    connector:
        timeout_seconds: 10
spec:
    provider:
        resources:
            exampleAccountA:
                static_resource:
                    plugin: mockcloudplugin
                    access_key: "123"
                dynamic_resource:
                    plugin: mockenergy
                    access_key: "435"
            exampleAccountB:
                static_resource:
                    plugin: mockcloudplugin
                    access_key: "435"
                dynamic_resource:
                    plugin: mockenergy
                    access_key: "435"
        environment:
            dynamic_environment:
                plugin: mockenergymix
                access_key: 7654asdE2
    server:
        port: 8088
