kind: carbonaut
meta:
    name: carbonaut
    log_level: debug
    connector:
        timeout_seconds: 10
spec:
    provider:
        resources:
            equinix:
                static_resource:
                    plugin: equinix
                    access_key_env: "METAL_AUTH_TOKEN"
                dynamic_resource:
                    plugin: mockenergy
                    access_key: "435"
        environment:
            dynamic_environment:
                plugin: mockenergymix
                access_key: 7654asdE2
    server:
        port: 8088
