FROM golang:1.22.2 as goenv

WORKDIR /connector

RUN apt update
RUN apt install bash

COPY . .

RUN go get ./...

RUN CGO_ENABLED=0 go build -o /go/bin/ main.go

FROM gcr.io/distroless/static-debian11 as prod

COPY --from=goenv go/bin /

CMD ["/main"]
