apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbonaut-deployment
  namespace: carbonaut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbonaut
  template:
    metadata:
      labels:
        app: carbonaut
    spec:
      containers:
      - name: carbonaut
        image: carbonaut:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: carbonaut-secrets
        volumeMounts:
        - name: config-volume
          mountPath: /etc/carbonaut
      volumes:
      - name: config-volume
        configMap:
          name: carbonaut-config
