apiVersion: v1
kind: Secret
metadata:
  name: carbonaut-secrets
  namespace: carbonaut
type: Opaque
data:
  # Base64 encode your secrets, e.g., echo -n 'my-api-key' | base64
  api-key: <your-base64-encoded-api-key>
