package electricitymap

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"

	"carbonaut.cloud/pkg/schema"
)

// Simple SDK to interact with some endpoints provided by the free version of the electricitymap.org API

type Provider struct{}

func getAuthKey() string {
	return os.Getenv("ELECTRICITY_MAP_KEY")
}

func (Provider) CollectEmission(zoneIdentifier string) (*schema.CarbonBreakdown, error) {
	authKey := getAuthKey()
	if authKey == "" {
		return nil, fmt.Errorf("no auth key found")
	}
	endpoint := "https://api-access.electricitymaps.com/free-tier/carbon-intensity/latest"
	client := &http.Client{}
	req, err := http.NewRequest(http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, fmt.Errorf("error while creating request: %w", err)
	}
	q := req.URL.Query()
	q.Add("zone", zoneIdentifier)
	req.URL.RawQuery = q.Encode()
	req.Header.Add("auth-token", authKey)
	req.Close = true
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error while scraping metrics: %w", err)
	}
	defer resp.Body.Close()

	// print out the response
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("error while reading response: %w", err)
	}
	carbonBreakdown, err := UnmarshalCarbonBreakdown(body)
	if err != nil {
		return nil, fmt.Errorf("error while unmarshalling response: %w", err)
	}
	return &schema.CarbonBreakdown{
		Zone:            carbonBreakdown.Zone,
		CarbonIntensity: carbonBreakdown.CarbonIntensity,
		Datetime:        carbonBreakdown.Datetime,
	}, nil
}

func UnmarshalCarbonBreakdown(data []byte) (CarbonBreakdown, error) {
	var r CarbonBreakdown
	err := json.Unmarshal(data, &r)
	return r, err
}

func (r *CarbonBreakdown) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

type CarbonBreakdown struct {
	Zone               string `json:"zone"`
	CarbonIntensity    int64  `json:"carbonIntensity"`
	Datetime           string `json:"datetime"`
	UpdatedAt          string `json:"updatedAt"`
	EmissionFactorType string `json:"emissionFactorType"`
	IsEstimated        bool   `json:"isEstimated"`
	EstimationMethod   string `json:"estimationMethod"`
}

// list created from endpoint https://api.electricitymap.org/v3/zones
var ElectricityMapZones = map[string]Region{
	"AD":         {ZoneName: "Andorra"},
	"AE":         {ZoneName: "United Arab Emirates"},
	"AF":         {ZoneName: "Afghanistan"},
	"AG":         {ZoneName: "Antigua and Barbuda"},
	"AL":         {ZoneName: "Albania"},
	"AM":         {ZoneName: "Armenia"},
	"AO":         {ZoneName: "Angola"},
	"AR":         {ZoneName: "Argentina"},
	"AT":         {ZoneName: "Austria"},
	"AU":         {ZoneName: "Australia"},
	"AU-LH":      {CountryName: "Australia", ZoneName: "Lord Howe Island"},
	"AU-NSW":     {CountryName: "Australia", ZoneName: "New South Wales"},
	"AU-NT":      {CountryName: "Australia", ZoneName: "Northern Territory"},
	"AU-QLD":     {CountryName: "Australia", ZoneName: "Queensland"},
	"AU-SA":      {CountryName: "Australia", ZoneName: "South Australia"},
	"AU-TAS":     {CountryName: "Australia", ZoneName: "Tasmania"},
	"AU-TAS-CBI": {CountryName: "Australia", ZoneName: "Cape Barren Island"}, "AU-TAS-FI": {CountryName: "Australia", ZoneName: "Flinders Island"}, "AU-TAS-KI": {CountryName: "Australia", ZoneName: "King Island"},
	"AU-VIC":     {CountryName: "Australia", ZoneName: "Victoria"},
	"AU-WA":      {CountryName: "Australia", ZoneName: "Western Australia"},
	"AU-WA-RI":   {CountryName: "Australia", ZoneName: "Rottnest Island"},
	"AW":         {ZoneName: "Aruba"},
	"AX":         {ZoneName: "Åland Islands"},
	"AZ":         {ZoneName: "Azerbaijan"},
	"BA":         {ZoneName: "Bosnia and Herzegovina"},
	"BB":         {ZoneName: "Barbados"},
	"BD":         {ZoneName: "Bangladesh"},
	"BE":         {ZoneName: "Belgium"},
	"BF":         {ZoneName: "Burkina Faso"},
	"BG":         {ZoneName: "Bulgaria"},
	"BH":         {ZoneName: "Bahrain"},
	"BI":         {ZoneName: "Burundi"},
	"BJ":         {ZoneName: "Benin"},
	"BN":         {ZoneName: "Brunei"},
	"BO":         {ZoneName: "Bolivia"},
	"BR":         {ZoneName: "Brazil"},
	"BR-CS":      {CountryName: "Brazil", ZoneName: "Central Brazil"},
	"BR-N":       {CountryName: "Brazil", ZoneName: "North Brazil"},
	"BR-NE":      {CountryName: "Brazil", ZoneName: "North-East Brazil"},
	"BR-S":       {CountryName: "Brazil", ZoneName: "South Brazil"},
	"BS":         {ZoneName: "Bahamas"},
	"BT":         {ZoneName: "Bhutan"},
	"BW":         {ZoneName: "Botswana"},
	"BY":         {ZoneName: "Belarus"},
	"BZ":         {ZoneName: "Belize"},
	"CA-AB":      {CountryName: "Canada", ZoneName: "Alberta"},
	"CA-BC":      {CountryName: "Canada", ZoneName: "British Columbia"},
	"CA-MB":      {CountryName: "Canada", ZoneName: "Manitoba"},
	"CA-NB":      {CountryName: "Canada", ZoneName: "New Brunswick"},
	"CA-NL-LB":   {CountryName: "Canada", ZoneName: "Labrador"},
	"CA-NL-NF":   {CountryName: "Canada", ZoneName: "Newfoundland"},
	"CA-NS":      {CountryName: "Canada", ZoneName: "Nova Scotia"},
	"CA-NT":      {CountryName: "Canada", ZoneName: "Northwest Territories"},
	"CA-NU":      {CountryName: "Canada", ZoneName: "Nunavut"},
	"CA-ON":      {CountryName: "Canada", ZoneName: "Ontario"},
	"CA-PE":      {CountryName: "Canada", ZoneName: "Prince Edward Island"},
	"CA-QC":      {CountryName: "Canada", ZoneName: "Québec"},
	"CA-SK":      {CountryName: "Canada", ZoneName: "Saskatchewan"},
	"CA-YT":      {CountryName: "Canada", ZoneName: "Yukon"},
	"CD":         {ZoneName: "Democratic Republic of the Congo"},
	"CF":         {ZoneName: "Central African Republic"},
	"CG":         {ZoneName: "Congo"},
	"CH":         {ZoneName: "Switzerland"},
	"CI":         {ZoneName: "Ivory Coast"},
	"CL-CHP":     {CountryName: "Chile", ZoneName: "Easter Island"},
	"CL-SEA":     {CountryName: "Chile", ZoneName: "Sistema Eléctrico de Aysén"},
	"CL-SEM":     {CountryName: "Chile", ZoneName: "Sistema Eléctrico de Magallanes"},
	"CL-SEN":     {CountryName: "Chile", ZoneName: "Sistema Eléctrico Nacional"},
	"CM":         {ZoneName: "Cameroon"},
	"CN":         {ZoneName: "China"},
	"CO":         {ZoneName: "Colombia"},
	"CR":         {ZoneName: "Costa Rica"},
	"CU":         {ZoneName: "Cuba"},
	"CV":         {ZoneName: "Cabo Verde"},
	"CY":         {ZoneName: "Cyprus"},
	"CZ":         {ZoneName: "Czechia"},
	"DE":         {ZoneName: "Germany"},
	"DJ":         {ZoneName: "Djibouti"},
	"DK":         {ZoneName: "Denmark"},
	"DK-BHM":     {CountryName: "Denmark", ZoneName: "Bornholm"},
	"DK-DK1":     {CountryName: "Denmark", ZoneName: "West Denmark"},
	"DK-DK2":     {CountryName: "Denmark", ZoneName: "East Denmark"},
	"DM":         {ZoneName: "Dominica"},
	"DO":         {ZoneName: "Dominican Republic"},
	"DZ":         {ZoneName: "Algeria"},
	"EC":         {ZoneName: "Ecuador"},
	"EE":         {ZoneName: "Estonia"},
	"EG":         {ZoneName: "Egypt"},
	"EH":         {ZoneName: "Western Sahara"},
	"ER":         {ZoneName: "Eritrea"},
	"ES":         {ZoneName: "Spain"},
	"ES-CE":      {CountryName: "Spain", ZoneName: "Ceuta"},
	"ES-CN-FVLZ": {CountryName: "Spain", ZoneName: "Fuerteventura/Lanzarote"}, "ES-CN-GC": {CountryName: "Spain", ZoneName: "Gran Canaria"},
	"ES-CN-HI": {CountryName: "Spain", ZoneName: "El Hierro"},
	"ES-CN-IG": {CountryName: "Spain", ZoneName: "Isla de la Gomera"},
	"ES-CN-LP": {CountryName: "Spain", ZoneName: "La Palma"},
	"ES-CN-TE": {CountryName: "Spain", ZoneName: "Tenerife"},
	"ES-IB-FO": {CountryName: "Spain", ZoneName: "Formentera"},
	"ES-IB-IZ": {CountryName: "Spain", ZoneName: "Ibiza"},
	"ES-IB-MA": {CountryName: "Spain", ZoneName: "Mallorca"},
	"ES-IB-ME": {CountryName: "Spain", ZoneName: "Menorca"},
	"ES-ML":    {CountryName: "Spain", ZoneName: "Melilla"},
	"ET":       {ZoneName: "Ethiopia"},
	"FI":       {ZoneName: "Finland"},
	"FJ":       {ZoneName: "Fiji"},
	"FK":       {ZoneName: "Falkland Islands"},
	"FM":       {ZoneName: "Micronesia"},
	"FO":       {ZoneName: "Faroe Islands"},
	"FO-MI":    {CountryName: "Faroe Islands", ZoneName: "Main Islands"},
	"FO-SI":    {CountryName: "Faroe Islands", ZoneName: "South Island"},
	"FR":       {ZoneName: "France"},
	"FR-COR":   {CountryName: "France", ZoneName: "Corsica"},
	"GA":       {ZoneName: "Gabon"},
	"GB":       {ZoneName: "Great Britain"},
	"GB-NIR":   {ZoneName: "Northern Ireland"},
	"GB-ORK":   {CountryName: "Great Britain", ZoneName: "Orkney Islands"},
	"GB-ZET":   {ZoneName: "Unknown"},
	"GE":       {ZoneName: "Georgia"},
	"GF":       {ZoneName: "French Guiana"},
	"GH":       {ZoneName: "Ghana"},
	"GL":       {ZoneName: "Greenland"},
	"GM":       {ZoneName: "Gambia"},
	"GN":       {ZoneName: "Guinea"},
	"GP":       {ZoneName: "Guadeloupe"},
	"GQ":       {ZoneName: "Equatorial Guinea"},
	"GR":       {ZoneName: "Greece"},
	"GR-IS":    {CountryName: "Greece", ZoneName: "Aegean Islands"},
	"GS":       {ZoneName: "South Georgia and the South Sandwich Islands"},
	"GT":       {ZoneName: "Guatemala"},
	"GU":       {ZoneName: "Guam"},
	"GW":       {ZoneName: "Guinea-Bissau"},
	"GY":       {ZoneName: "Guyana"},
	"HK":       {ZoneName: "Hong Kong"},
	"HM":       {ZoneName: "Heard Island and McDonald Islands"},
	"HN":       {ZoneName: "Honduras"},
	"HR":       {ZoneName: "Croatia"},
	"HT":       {ZoneName: "Haiti"},
	"HU":       {ZoneName: "Hungary"},
	"ID":       {ZoneName: "Indonesia"},
	"IE":       {ZoneName: "Ireland"},
	"IL":       {ZoneName: "Israel"},
	"IM":       {ZoneName: "Isle of Man"},
	"IN":       {ZoneName: "Mainland India"},
	"IN-AN":    {CountryName: "India", ZoneName: "Andaman and Nicobar Islands"}, "IN-DL": {CountryName: "India", ZoneName: "Delhi"},
	"IN-EA":        {CountryName: "India", ZoneName: "Eastern India"},
	"IN-HP":        {CountryName: "India", ZoneName: "Himachal Pradesh"},
	"IN-KA":        {CountryName: "India", ZoneName: "Karnataka"},
	"IN-MH":        {CountryName: "India", ZoneName: "Maharashtra"},
	"IN-NE":        {CountryName: "India", ZoneName: "North Eastern India"},
	"IN-NO":        {CountryName: "India", ZoneName: "Northern India"},
	"IN-PB":        {CountryName: "India", ZoneName: "Punjab"},
	"IN-SO":        {CountryName: "India", ZoneName: "Southern India"},
	"IN-UP":        {CountryName: "India", ZoneName: "Uttar Pradesh"},
	"IN-UT":        {CountryName: "India", ZoneName: "Uttarakhand"},
	"IN-WE":        {CountryName: "India", ZoneName: "Western India"},
	"IQ":           {ZoneName: "Iraq"},
	"IQ-KUR":       {CountryName: "Iraq", ZoneName: "Kurdistan"},
	"IR":           {ZoneName: "Iran"},
	"IS":           {ZoneName: "Iceland"},
	"IT":           {ZoneName: "Italy"},
	"IT-CNO":       {CountryName: "Italy", ZoneName: "Central North Italy"},
	"IT-CSO":       {CountryName: "Italy", ZoneName: "Central South Italy"},
	"IT-NO":        {CountryName: "Italy", ZoneName: "North Italy"},
	"IT-SAR":       {CountryName: "Italy", ZoneName: "Sardinia"},
	"IT-SIC":       {CountryName: "Italy", ZoneName: "Sicily"},
	"IT-SO":        {CountryName: "Italy", ZoneName: "South Italy"},
	"JM":           {ZoneName: "Jamaica"},
	"JO":           {ZoneName: "Jordan"},
	"JP":           {ZoneName: "Japan"},
	"JP-CB":        {CountryName: "Japan", ZoneName: "Chūbu"},
	"JP-CG":        {CountryName: "Japan", ZoneName: "Chūgoku"},
	"JP-HKD":       {CountryName: "Japan", ZoneName: "Hokkaidō"},
	"JP-HR":        {CountryName: "Japan", ZoneName: "Hokuriku"},
	"JP-KN":        {CountryName: "Japan", ZoneName: "Kansai"},
	"JP-KY":        {CountryName: "Japan", ZoneName: "Kyūshū"},
	"JP-ON":        {CountryName: "Japan", ZoneName: "Okinawa"},
	"JP-SK":        {CountryName: "Japan", ZoneName: "Shikoku"},
	"JP-TH":        {CountryName: "Japan", ZoneName: "Tōhoku"},
	"JP-TK":        {CountryName: "Japan", ZoneName: "Tōkyō"},
	"KE":           {ZoneName: "Kenya"},
	"KG":           {ZoneName: "Kyrgyzstan"},
	"KH":           {ZoneName: "Cambodia"},
	"KM":           {ZoneName: "Comoros"},
	"KP":           {ZoneName: "North Korea"},
	"KR":           {ZoneName: "South Korea"},
	"KW":           {ZoneName: "Kuwait"},
	"KZ":           {ZoneName: "Kazakhstan"},
	"LA":           {ZoneName: "Laos"},
	"LB":           {ZoneName: "Lebanon"},
	"LC":           {ZoneName: "Saint Lucia"},
	"LI":           {ZoneName: "Liechtenstein"},
	"LK":           {ZoneName: "Sri Lanka"},
	"LR":           {ZoneName: "Liberia"},
	"LS":           {ZoneName: "Lesotho"},
	"LT":           {ZoneName: "Lithuania"},
	"LU":           {ZoneName: "Luxembourg"},
	"LV":           {ZoneName: "Latvia"},
	"LY":           {ZoneName: "Libya"},
	"MA":           {ZoneName: "Morocco"},
	"MD":           {ZoneName: "Moldova"},
	"ME":           {ZoneName: "Montenegro"},
	"MG":           {ZoneName: "Madagascar"},
	"MK":           {ZoneName: "North Macedonia"},
	"ML":           {ZoneName: "Mali"},
	"MM":           {ZoneName: "Myanmar"},
	"MN":           {ZoneName: "Mongolia"},
	"MQ":           {ZoneName: "Martinique"},
	"MR":           {ZoneName: "Mauritania"},
	"MT":           {ZoneName: "Malta"},
	"MU":           {ZoneName: "Mauritius"},
	"MW":           {ZoneName: "Malawi"},
	"MX":           {ZoneName: "Mexico"},
	"MX-BC":        {CountryName: "Mexico", ZoneName: "Baja California"},
	"MX-BCS":       {ZoneName: "Unknown"},
	"MX-CE":        {CountryName: "Mexico", ZoneName: "Central"},
	"MX-NE":        {CountryName: "Mexico", ZoneName: "North East"},
	"MX-NO":        {CountryName: "Mexico", ZoneName: "North"},
	"MX-NW":        {CountryName: "Mexico", ZoneName: "North West"},
	"MX-OC":        {CountryName: "Mexico", ZoneName: "Occidental"},
	"MX-OR":        {CountryName: "Mexico", ZoneName: "Oriental"},
	"MX-PN":        {CountryName: "Mexico", ZoneName: "Peninsula"},
	"MY-EM":        {CountryName: "Malaysia", ZoneName: "Borneo"},
	"MY-WM":        {CountryName: "Malaysia", ZoneName: "Peninsula"},
	"MZ":           {ZoneName: "Mozambique"},
	"NA":           {ZoneName: "Namibia"},
	"NC":           {ZoneName: "New Caledonia"},
	"NE":           {ZoneName: "Niger"},
	"NG":           {ZoneName: "Nigeria"},
	"NI":           {ZoneName: "Nicaragua"},
	"NKR":          {ZoneName: "Nagorno-Karabakh"},
	"NL":           {ZoneName: "Netherlands"},
	"NO":           {ZoneName: "Norway"},
	"NO-NO1":       {CountryName: "Norway", ZoneName: "Southeast Norway"},
	"NO-NO2":       {CountryName: "Norway", ZoneName: "Southwest Norway"},
	"NO-NO3":       {CountryName: "Norway", ZoneName: "Middle Norway"},
	"NO-NO4":       {CountryName: "Norway", ZoneName: "North Norway"},
	"NO-NO5":       {CountryName: "Norway", ZoneName: "West Norway"},
	"NP":           {ZoneName: "Nepal"},
	"NZ":           {ZoneName: "New Zealand"},
	"NZ-NZA":       {CountryName: "New Zealand", ZoneName: "Auckland Islands"},
	"NZ-NZC":       {CountryName: "New Zealand", ZoneName: "Chatham Islands"},
	"NZ-NZST":      {CountryName: "New Zealand", ZoneName: "Stewart Island"},
	"OM":           {ZoneName: "Oman"},
	"PA":           {ZoneName: "Panama"},
	"PE":           {ZoneName: "Peru"},
	"PF":           {ZoneName: "French Polynesia"},
	"PG":           {ZoneName: "Papua New Guinea"},
	"PH":           {ZoneName: "Philippines"},
	"PH-LU":        {CountryName: "Philippines", ZoneName: "Luzon"},
	"PH-MI":        {CountryName: "Philippines", ZoneName: "Mindanao"},
	"PH-VI":        {CountryName: "Philippines", ZoneName: "Visayas"},
	"PK":           {ZoneName: "Pakistan"},
	"PL":           {ZoneName: "Poland"},
	"PM":           {ZoneName: "Saint Pierre and Miquelon"},
	"PR":           {ZoneName: "Puerto Rico"},
	"PS":           {ZoneName: "State of Palestine"},
	"PT":           {ZoneName: "Portugal"},
	"PT-AC":        {CountryName: "Portugal", ZoneName: "Azores"},
	"PT-MA":        {CountryName: "Portugal", ZoneName: "Madeira"},
	"PW":           {ZoneName: "Palau"},
	"PY":           {ZoneName: "Paraguay"},
	"QA":           {ZoneName: "Qatar"},
	"RE":           {ZoneName: "Réunion"},
	"RO":           {ZoneName: "Romania"},
	"RS":           {ZoneName: "Serbia"},
	"RU":           {ZoneName: "Russia"},
	"RU-1":         {CountryName: "Russia", ZoneName: "Europe-Ural"},
	"RU-2":         {CountryName: "Russia", ZoneName: "Siberia"},
	"RU-AS":        {CountryName: "Russia", ZoneName: "East"},
	"RU-EU":        {CountryName: "Russia", ZoneName: "Arctic"},
	"RU-FE":        {CountryName: "Russia", ZoneName: "Far East"},
	"RU-KGD":       {CountryName: "Russia", ZoneName: "Kaliningrad"},
	"RW":           {ZoneName: "Rwanda"},
	"SA":           {ZoneName: "Saudi Arabia"},
	"SB":           {ZoneName: "Solomon Islands"},
	"SD":           {ZoneName: "Sudan"},
	"SE":           {ZoneName: "Sweden"},
	"SE-SE1":       {CountryName: "Sweden", ZoneName: "North Sweden"},
	"SE-SE2":       {CountryName: "Sweden", ZoneName: "North Central Sweden"},
	"SE-SE3":       {CountryName: "Sweden", ZoneName: "South Central Sweden"},
	"SE-SE4":       {CountryName: "Sweden", ZoneName: "South Sweden"},
	"SG":           {ZoneName: "Singapore"},
	"SI":           {ZoneName: "Slovenia"},
	"SJ":           {ZoneName: "Svalbard and Jan Mayen"},
	"SK":           {ZoneName: "Slovakia"},
	"SL":           {ZoneName: "Sierra Leone"},
	"SN":           {ZoneName: "Senegal"},
	"SO":           {ZoneName: "Somalia"},
	"SR":           {ZoneName: "Suriname"},
	"SS":           {ZoneName: "South Sudan"},
	"ST":           {ZoneName: "Sao Tome and Principe"},
	"SV":           {ZoneName: "El Salvador"},
	"SY":           {ZoneName: "Syria"},
	"SZ":           {ZoneName: "Swaziland"},
	"TD":           {ZoneName: "Chad"},
	"TF":           {ZoneName: "French Southern Territories"},
	"TG":           {ZoneName: "Togo"},
	"TH":           {ZoneName: "Thailand"},
	"TJ":           {ZoneName: "Tajikistan"},
	"TL":           {ZoneName: "Timor-Leste"},
	"TM":           {ZoneName: "Turkmenistan"},
	"TN":           {ZoneName: "Tunisia"},
	"TO":           {ZoneName: "Tonga"},
	"TR":           {ZoneName: "Turkey"},
	"TT":           {ZoneName: "Trinidad and Tobago"},
	"TW":           {ZoneName: "Taiwan"},
	"TZ":           {ZoneName: "Tanzania"},
	"UA":           {ZoneName: "Ukraine"},
	"UA-CR":        {CountryName: "Ukraine", ZoneName: "Crimea"},
	"UG":           {ZoneName: "Uganda"},
	"US":           {ZoneName: "Contiguous United States"},
	"US-AK":        {CountryName: "USA", ZoneName: "Alaska"},
	"US-CAL-BANC":  {CountryName: "USA", ZoneName: "Balancing Authority Of Northern California"},
	"US-CAL-CISO":  {CountryName: "USA", ZoneName: "California Independent System Operator"},
	"US-CAL-IID":   {CountryName: "USA", ZoneName: "Imperial Irrigation District"},
	"US-CAL-LDWP":  {CountryName: "USA", ZoneName: "Los Angeles Department Of Water And Power"},
	"US-CAL-TIDC":  {CountryName: "USA", ZoneName: "Turlock Irrigation District"},
	"US-CAR-CPLE":  {CountryName: "USA", ZoneName: "Duke Energy Progress East"},
	"US-CAR-CPLW":  {CountryName: "USA", ZoneName: "Duke Energy Progress West"},
	"US-CAR-DUK":   {CountryName: "USA", ZoneName: "Duke Energy Carolinas"},
	"US-CAR-SC":    {CountryName: "USA", ZoneName: "South Carolina Public Service Authority"},
	"US-CAR-SCEG":  {CountryName: "USA", ZoneName: "South Carolina Electric & Gas Company"},
	"US-CAR-YAD":   {CountryName: "USA", ZoneName: "Alcoa Power Generating, Inc. Yadkin Division"},
	"US-CENT-SPA":  {CountryName: "USA", ZoneName: "Southwestern Power Administration"},
	"US-CENT-SWPP": {CountryName: "USA", ZoneName: "Southwest Power Pool"},
	"US-FLA-FMPP":  {CountryName: "USA", ZoneName: "Florida Municipal Power Pool"},
	"US-FLA-FPC":   {CountryName: "USA", ZoneName: "Duke Energy Florida Inc"},
	"US-FLA-FPL":   {CountryName: "USA", ZoneName: "Florida Power & Light Company"},
	"US-FLA-GVL":   {CountryName: "USA", ZoneName: "Gainesville Regional Utilities"},
	"US-FLA-HST":   {CountryName: "USA", ZoneName: "City Of Homestead"},
	"US-FLA-JEA":   {CountryName: "USA", ZoneName: "Jacksonville Electric Authority"},
	"US-FLA-SEC":   {CountryName: "USA", ZoneName: "Seminole Electric Cooperative"},
	"US-FLA-TAL":   {CountryName: "USA", ZoneName: "City Of Tallahassee"}, "US-FLA-TEC": {CountryName: "USA", ZoneName: "Tampa Electric Company"}, "US-HI-HA": {CountryName: "USA", ZoneName: "Hawaii"},
	"US-HI-KA":     {CountryName: "USA", ZoneName: "Kauai"},
	"US-HI-KH":     {CountryName: "USA", ZoneName: "Kahoolawe"},
	"US-HI-LA":     {CountryName: "USA", ZoneName: "Lanai"},
	"US-HI-MA":     {CountryName: "USA", ZoneName: "Maui"},
	"US-HI-MO":     {CountryName: "USA", ZoneName: "Molokai"},
	"US-HI-NI":     {CountryName: "USA", ZoneName: "Niihau"},
	"US-HI-OA":     {CountryName: "USA", ZoneName: "Oahu"},
	"US-MIDA-PJM":  {CountryName: "USA", ZoneName: "PJM Interconnection, Llc"},
	"US-MIDW-AECI": {CountryName: "USA", ZoneName: "Associated Electric Cooperative, Inc."},
	"US-MIDW-LGEE": {CountryName: "USA", ZoneName: "Louisville Gas And Electric Company And Kentucky Utilities"},
	"US-MIDW-MISO": {CountryName: "USA", ZoneName: "Midcontinent Independent Transmission System Operator, Inc."},
	"US-NE-ISNE":   {CountryName: "USA", ZoneName: "Iso New England Inc."},
	"US-NW-AVA":    {CountryName: "USA", ZoneName: "Avista Corporation"},
	"US-NW-BPAT":   {CountryName: "USA", ZoneName: "Bonneville Power Administration"},
	"US-NW-CHPD":   {CountryName: "USA", ZoneName: "PUD No. 1 Of Chelan County"},
	"US-NW-DOPD":   {CountryName: "USA", ZoneName: "PUD No. 1 Of Douglas County"},
	"US-NW-GCPD":   {CountryName: "USA", ZoneName: "PUD No. 2 Of Grant County, Washington"},
	"US-NW-GRID":   {CountryName: "USA", ZoneName: "Gridforce Energy Management, Llc"},
	"US-NW-GWA":    {CountryName: "USA", ZoneName: "Naturener Power Watch, Llc (Gwa)"},
	"US-NW-IPCO":   {CountryName: "USA", ZoneName: "Idaho Power Company"},
	"US-NW-NEVP":   {CountryName: "USA", ZoneName: "Nevada Power Company"},
	"US-NW-NWMT":   {CountryName: "USA", ZoneName: "Northwestern Energy"},
	"US-NW-PACE":   {CountryName: "USA", ZoneName: "Pacificorp East"},
	"US-NW-PACW":   {CountryName: "USA", ZoneName: "Pacificorp West"}, "US-NW-PGE": {CountryName: "USA", ZoneName: "Portland General Electric Company"},
	"US-NW-PSCO": {CountryName: "USA", ZoneName: "Public Service Company Of Colorado"},
	"US-NW-PSEI": {CountryName: "USA", ZoneName: "Puget Sound Energy"},
	"US-NW-SCL":  {CountryName: "USA", ZoneName: "Seattle City Light"},
	"US-NW-TPWR": {CountryName: "USA", ZoneName: "City Of Tacoma, Department Of Public Utilities, Light Division"},
	"US-NW-WACM": {CountryName: "USA", ZoneName: "Western Area Power Administration - Rocky Mountain Region"}, "US-NW-WAUW": {CountryName: "USA", ZoneName: "Western Area Power Administration UGP West"},
	"US-NW-WWA":   {CountryName: "USA", ZoneName: "Naturener Wind Watch, Llc"},
	"US-NY-NYIS":  {CountryName: "USA", ZoneName: "New York Independent System Operator"},
	"US-SE-SEPA":  {CountryName: "USA", ZoneName: "Southeastern Power Administration"},
	"US-SE-SOCO":  {CountryName: "USA", ZoneName: "Southern Company Services, Inc. - Trans"},
	"US-SW-AZPS":  {CountryName: "USA", ZoneName: "Arizona Public Service Company"},
	"US-SW-EPE":   {CountryName: "USA", ZoneName: "El Paso Electric Company"},
	"US-SW-GRIF":  {CountryName: "USA", ZoneName: "Griffith Energy, LLC"},
	"US-SW-PNM":   {CountryName: "USA", ZoneName: "Public Service Company Of New Mexico"},
	"US-SW-SRP":   {CountryName: "USA", ZoneName: "Salt River Project"},
	"US-SW-TEPC":  {CountryName: "USA", ZoneName: "Tucson Electric Power Company"},
	"US-SW-WALC":  {CountryName: "USA", ZoneName: "Western Area Power Administration - Desert Southwest Region"},
	"US-TEN-TVA":  {CountryName: "USA", ZoneName: "Tennessee Valley Authority"},
	"US-TEX-ERCO": {CountryName: "USA", ZoneName: "Electric Reliability Council Of Texas, Inc."},
	"UY":          {ZoneName: "Uruguay"},
	"UZ":          {ZoneName: "Uzbekistan"},
	"VC":          {ZoneName: "Saint Vincent and the Grenadines"},
	"VE":          {ZoneName: "Venezuela"},
	"VI":          {CountryName: "USA", ZoneName: "Virgin Islands"},
	"VN":          {ZoneName: "Vietnam"},
	"VN-C":        {CountryName: "Vietnam", ZoneName: "Central Vietnam"},
	"VN-N":        {CountryName: "Vietnam", ZoneName: "Northern Vietnam"},
	"VN-S":        {CountryName: "Vietnam", ZoneName: "Southern Vietnam"},
	"VU":          {ZoneName: "Vanuatu"},
	"WS":          {ZoneName: "Samoa"},
	"XK":          {ZoneName: "Kosovo"},
	"XX":          {ZoneName: "Northern Cyprus"},
	"YE":          {ZoneName: "Yemen"},
	"YT":          {ZoneName: "Mayotte"},
	"ZA":          {ZoneName: "South Africa"},
	"ZM":          {ZoneName: "Zambia"},
	"ZW":          {ZoneName: "Zimbabwe"},
}

type Ad struct {
	ZoneName string `json:ZoneName`
}

type Region struct {
	CountryName string `json:CountryName`
	ZoneName    string `json:ZoneName`
}
