name: Go Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: Run Coverage Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Run Coverage Tests
        run: |
          chmod +x coverage.sh
          ./coverage.sh
        env:
          TEST_TIMEOUT: 800 # or adjust as needed
        shell: bash

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: coverage.html
