apiVersion: v1
kind: ConfigMap
metadata:
  name: carbonaut-config
  namespace: carbonaut
data:
  carbonaut.yaml: |
    kind: carbonaut
    meta:
        name: carbonaut
        log_level: info
        connector:
            timeout_seconds: 10
    spec:
        provider:
            resources:
                equinix:
                    static_resource:
                        plugin: equinix
                        access_key_env: "METAL_AUTH_TOKEN"
                    dynamic_resource:
                        plugin: scaphandre
                        endpoint: ":8080/metrics"
            environment:
                dynamic_environment:
                    plugin: electricitymaps
                    access_key_env: "ELECTRICITY_MAP_AUTH_TOKEN"
        server:
            port: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbonaut-deployment
  namespace: carbonaut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbonaut
  template:
    metadata:
      labels:
        app: carbonaut
    spec:
      containers:
      - name: carbonaut
        image: leonardpahlke/carbonaut:latest
        args: ["-c", "/etc/config/carbonaut.yaml"]
        ports:
        - containerPort: 8088
        env:
        - name: CONFIG_PATH
          value: "/etc/config/carbonaut.yaml"
        envFrom:
        - secretRef:
            name: carbonaut-secrets
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: carbonaut-config
          items:
            - key: carbonaut.yaml
              path: carbonaut.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: carbonaut-service
  namespace: carbonaut
spec:
  selector:
    app: carbonaut
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
